=== michael-andreuzza/uicollective.org/.astro/collections/directory.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "domain": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "Trusted",
        "Under Review",
        "Not Verified",
        "Removed from Trusted Status"
      ]
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "domain",
    "status",
    "updatedAt"
  ]
}

=== michael-andreuzza/uicollective.org/src/content/directory.json
[
  {
    "name": "Aceterniry",
    "domain": "aceterniry.com",
    "status": "Trusted",
    "updatedAt": "2026-04-12"
  },
  {
    "name": "Shadcnblocks",
    "domain": "shadcnblocks.com",
    "status": "Trusted",
    "updatedAt": "2026-04-20"
  },
  {
    "name": "Lexington Themes",
    "domain": "lexingtonthemes.com",
    "status": "Trusted",
    "updatedAt": "2026-04-18"
  },
  {
    "name": "Tailark",
    "domain": "tailark.com",
    "status": "Trusted",
    "updatedAt": "2026-04-12"
  },
  {
    "name": "Wicked Blocks",
    "domain": "wickedbocks.dev",
    "status": "Trusted",
    "updatedAt": "2026-04-20"
  },
  {
    "name": "Oxbow UI",
    "domain": "oxbowui.com",
    "status": "Trusted",
    "updatedAt": "2026-04-20"
  },
  {
    "name": "Wicked Templates",
    "domain": "wickedtemplates.com",
    "status": "Trusted",
    "updatedAt": "2026-04-20"
  },
  {
    "name": "Bearnie",
    "domain": "bearnie.dev",
    "status": "Trusted",
    "updatedAt": "2026-04-20"
  },
  {
    "name": "Aumata",
    "domain": "aumata.ai",
    "status": "Removed",
    "updatedAt": "2026-04-20"
  }
]
